# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:  

  - job: linux
    pool: 
      vmImage: 'ubuntu-latest'
    steps:

    - task: gitversion/setup@0
      inputs:
        versionSpec: '5.6.0'

    - task: gitversion/execute@0
      inputs:
        useConfigFile: true
        configFilePath: 'gitversion.yml'   
  
    - task: Docker@2
      displayName: Build the image
      inputs:
        containerRegistry: 'Docker Hub'
        repository: 'jasase/deconztomqtt'
        command: 'build'
        Dockerfile: '**/Dockerfile'
        buildContext: '$(Build.SourcesDirectory)/src'
        tags: |
          $(GitVersion.NuGetVersionV2)
          latest
          
    - task: Docker@2
      displayName: Push the image
      condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
      inputs:
        containerRegistry: 'Docker Hub'
        repository: 'jasase/deconztomqtt'
        command: 'push'
        tags: |
          $(GitVersion.NuGetVersionV2)
          latest
  